# Generated by Django 4.1.5 on 2023-03-29 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=20)),
                ('birthDay', models.CharField(max_length=10)),
                ('chatID', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('discont', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('cachBack', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.IntegerField(verbose_name='Кол-во')),
                ('nikotin', models.IntegerField(blank=True, null=True, verbose_name='Никотин мг')),
                ('total_count', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('count_of_sold', models.IntegerField(blank=True, default='0', null=True)),
                ('info', models.TextField(blank=True, max_length=250, null=True, verbose_name='Доп.информация')),
                ('img', models.ImageField(blank=True, default='img/salt.jpg', null=True, upload_to='img/')),
                ('type', models.TextField(blank=True, default='Mix', null=True, verbose_name='Тип продукции')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Теги:')),
            ],
        ),
    ]
